# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
    ]
