# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_auto_20180303_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
    ]
