# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_auto_20180303_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
