# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='account_name',
            field=models.CharField(default=1, max_length=50, verbose_name='account name'),
            preserve_default=False,
        ),
    ]
