# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_agent_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default=1, max_length=25, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default=1, max_length=25, verbose_name='name'),
            preserve_default=False,
        ),
    ]
