# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0013_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
    ]
