# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_auto_20180311_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='savings.Parent'),
            preserve_default=False,
        ),
    ]
