# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0017_savingsplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='child',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='amount_to_be_saved',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='school',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
