# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0018_auto_20180311_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsplan',
            name='target_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='target_term',
            field=models.CharField(choices=[('', 'Choose...'), ('1', 'First Term - Sep. 20'), ('2', 'First Term - Jan. 10'), ('3', 'First Term - Apr. 15')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
