# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_auto_20180311_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_fee', models.IntegerField()),
                ('amount_to_be_saved', models.IntegerField()),
                ('frequency', models.CharField(choices=[('', 'Choose...'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=7)),
                ('target_term', models.CharField(choices=[('', 'Choose...'), ('1', '1st Term - Sep. 20'), ('2', '2nd Term - Jan. 10'), ('3', '3rd Term - Apr. 15')], max_length=1)),
                ('target_date', models.DateTimeField()),
                ('contribution', models.PositiveSmallIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='parent',
        ),
        migrations.DeleteModel(
            name='SavingsPlan',
        ),
    ]
