# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0020_auto_20180312_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='target_date',
            field=models.DateField(),
        ),
    ]
