# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0021_auto_20180312_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='mode_of_payment',
            field=models.CharField(choices=[('', 'Choose...'), ('agent', 'Agent'), ('direct debit', 'Direct debit')], default='agent', max_length=15),
            preserve_default=False,
        ),
    ]
