# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0025_saving_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingplan',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='saving',
            name='amount',
            field=models.PositiveSmallIntegerField(default=37000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saving',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
