# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0027_auto_20180327_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
